condense_wildcard_suffixes = true
fn_single_line = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true
wrap_comments = true