[package]
name = "mysqlow"
version = "0.1.0"
authors = ["Ulrich Schmidt-Goertz"]
homepage = "https://github.com/ulrichsg/mysqlow"

[dependencies]
chrono = "0.4.7"
rayon = "1.3.0"
regex = "1.2.0"
sha1 = "0.6.0"
sqlparser = "0.5.0"
structopt = "0.2.18"
